version: '3'
services:
  postgres:
    image: 'postgres'
    container_name: 'postgres_electronics_store'
    environment:
      POSTGRES_DB: 'postgres'
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
    ports:
      - '5432:5432'
